import { Geist, Geist_Mono } from 'next/font/google'

import RootProvider from '@/app/RootProvider'
import { GlobalNav } from '@/app/_components/gnb'

import type { Metadata } from 'next'

import './_style/globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<RootProvider>
					<div id="root">
						<GlobalNav />
						{children}
					</div>
				</RootProvider>
			</body>
		</html>
	)
}
